### ISSUE TITLE
User roles and permissions for managing events

### ISSUE THREAD

**Issue by joergrs** [gruenes-brett/webseite#24]
# Roles and capabilities

Wordpress defines a default set of [roles and capabilities](https://wordpress.org/support/article/roles-and-capabilities/) that mainly matches what we need.

## anonymous users
* Create events that are private by default

## authors
* Edit own events
* Event is private by default

## editors
* Edit any event
* Set any event public

## administrator
* Edit any event
* Set any event public
* Edit categories

# Definitions
Edit = creating/changing/deleting

**Comment by sebastianlay** [comment]
TODO: authors should be able to make their own events public (and public should be the default)

**Comment by sebastianlay** [comment]
🎉
