### ISSUE TITLE
Nightly backup of the WordPress database

### ISSUE THREAD

**Issue by joergrs** [gruenes-brett/webseite#36]
A cron job that runs every night at 3:00 that creates a backup of the database of the current WordPress instance.

* Target path: `/var/www/gb_backup/<instance_name>/db_<timestamp>.sql`
* Command: `wp db export <target path>`

Another cron job deletes all backups that are older than a week. Run at 2:30 every night.

**Comment by sebastianlay** [comment]
We should also think about an off-site backup in case of a harddrive failure.
