### ISSUE TITLE
iCal: add `URL` field

### ISSUE THREAD

**Issue by astro** [gruenes-brett/webseite#54]
I am [aggregating events](https://ticker.c3d2.de/), wanting to link back.

**Comment by joergrs** [comment]
Added fields URL, CATEGORIES and LOCATION.

Our REST API may also be useful for querying event data: https://github.com/gruenes-brett/community-calendar/issues/37

E.g.: https://dresden.gruenesbrett.net/wp-json/comcal/v1/event/all/
